<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>se.mdu</groupId>
    <artifactId>mdu-oss-parent</artifactId>
    <version>64</version>
    <relativePath>../mdu-oss-parent/pom.xml</relativePath>
  </parent>

  <groupId>se.mdu.nuspec</groupId>
  <artifactId>mdu-nuspec-modell</artifactId>
  <version>2.0.0-SNAPSHOT</version>

  <name>${project.groupId}:${project.artifactId}</name>
  <description>Modeller för nuspec-filer.</description>

  <scm>
    <connection>scm:git:https://github.com/mdh-se/${project.artifactId}.git</connection>
    <developerConnection>scm:git:https://github.com/mdh-se/${project.artifactId}.git</developerConnection>
    <tag>HEAD</tag>
    <url>https://github.com/mdh-se/${project.artifactId}</url>
  </scm>

  <dependencies>
    <dependency>
      <groupId>jakarta.validation</groupId>
      <artifactId>jakarta.validation-api</artifactId>
    </dependency>
    <dependency>
      <groupId>jakarta.xml.bind</groupId>
      <artifactId>jakarta.xml.bind-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <!-- Implementation javax.xml.bind -->
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <scope>runtime</scope>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>com.github.spotbugs</groupId>
          <artifactId>spotbugs-maven-plugin</artifactId>
          <configuration>
            <excludeFilterFile>spotbugs-exclude.xml</excludeFilterFile>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-checkstyle-plugin</artifactId>
          <configuration>
            <!-- Exclude the generated sources -->
            <excludes>se/mdu/nuspec/modell/**/*.java</excludes>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-pmd-plugin</artifactId>
          <configuration>
            <!-- Exclude the generated sources -->
            <excludes>
              <exclude>se/mdu/nuspec/modell/**/*.java</exclude>
            </excludes>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.cxf</groupId>
        <artifactId>cxf-xjc-plugin</artifactId>
        <executions>
          <execution>
            <id>generate-sources</id>
            <goals>
              <goal>xsdtojava</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <xsdOptions>
            <xsdOption>
              <packagename>se.mdu.nuspec.modell</packagename>
            </xsdOption>
          </xsdOptions>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
